server:
  port: 10086
  max-http-header-size: 10000000
spring:
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    #&databaseuseUnicode=true&characterEncoding=utf8&autoReconnect=true
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&databaseuseUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
  # 多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
  # 设置 为true ,即 允许 同名
  main:
    allow-bean-definition-overriding: true
  task:
    # Spring 执行器配置，对应 TaskExecutionProperties 配置类。对于 Spring 异步任务，会使用该执行器。
    execution:
      thread-name-prefix: my-async-  # 线程池的线程名的前缀。默认为 task- ，建议根据自己应用来设置
      pool: # 线程池相关
        core-size: 100 # 核心线程数，线程池创建时候初始化的线程数。默认为 8 。
        max-size: 500 # 最大线程数，线程池最大的线程数，只有在缓冲队列满了之后，才会申请超过核心线程数的线程。默认为 Integer.MAX_VALUE
        keep-alive: 60s # 允许线程的空闲时间，当超过了核心线程之外的线程，在空闲时间到达之后会被销毁。默认为 60 秒
        queue-capacity: 100 # 缓冲队列大小，用来缓冲执行任务的队列的大小。默认为 Integer.MAX_VALUE 。
        #Whether core threads are allowed to time out. This enables dynamic growing and	 shrinking of the pool.
        allow-core-thread-timeout: false # 是否允许核心线程超时，即开启线程池的动态增长和缩小。默认为 true 。 保留核心线程数目的,防止重新初始化线程
      shutdown:
        await-termination: true #是否等待异步任务执行完成 Whether the executor should wait for scheduled tasks to complete on shutdown.
        await-termination-period: 60 #等待周期 Maximum time the executor should wait for remaining tasks to complete.
  jackson:
    date-format: java.text.SimpleDateFormat
thread:
  pool:
    coreSize: 500
    maxSize: 2000
    keepAlive: 60
    blockingSize: 5000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl